# UI Fix Workflow Configuration
name: "ui-fix"
description: "Lightweight UI/UX change workflow - 2 steps for visual changes"
author: "QDM Team"
version: "1.0.0"

# Config reference (bmb standard)
config_source: "{project-root}/{qdm_root}/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
skill_level: "{config_source}:skill_level"
sdd_root: "{config_source}:sdd_root"
date: system-generated

# Module paths
installed_path: "{project-root}/{qdm_root}/workflows/ui-fix"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.md"
steps_path: "{installed_path}/steps"

# Output settings
default_output_folder: "{sdd_root}/ui-{{ui_name}}"
default_output_file: "{default_output_folder}/status.md"

# Templates
template_meta: "{project-root}/{qdm_root}/templates/ui/meta.yaml.template"
template_status: "{project-root}/{qdm_root}/templates/ui/status.md.template"

# Workflow settings
standalone: true
complexity: lightweight
max_files: 2
max_time_minutes: 30
